
import DAO.ConnectionProvider;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author OPR
 */
public class SearchSw extends javax.swing.JFrame {
String loc;
int SN;
int f=0;
    /**
     * Creates new form SearchSw
     */
    public SearchSw() {
        initComponents();
        Color col=new Color(215,243,243);
        getContentPane().setBackground(col);
        if(Home.URole.equals("Admin")){
            
            btnUpd.setVisible(false);
            btnFinish.setVisible(false);
        }
    }
    
    public SearchSw(String res){
        initComponents();
        Color col=new Color(215,243,243);
        getContentPane().setBackground(col);
        tableLoc.setEnabled(false);
        btnFinish.setVisible(false);
       
            labName.setVisible(false);
            
           
            txtEqName.setVisible(false);
            
            btnAdDev.setVisible(false);
            btnUpDev.setVisible(false);
        if(Home.URole.equals("Admin")){
            btnUpd.setVisible(false);
        }
        try{
                
                Connection con=ConnectionProvider.getCon();
                Statement st=con.createStatement();
                ResultSet rs=st.executeQuery("select * from SwPkg");
                while(rs.next()){
                    String id=rs.getString("swID");
//                    System.out.println("hey");
                    if(id.equalsIgnoreCase(res)){
                        txtID.setText(rs.getString("swID")); txtID.setEditable(false);
                        txtName.setText(rs.getString("name")); txtName.setEditable(false);
                        txtSize.setText(rs.getString("size")); txtSize.setEditable(false);
                        txtUpd.setText(rs.getString("dateOfUpdation")); txtUpd.setEditable(false);
                        txtRev.setText(rs.getString("revNo")); txtRev.setEditable(false);
                        
                    } 
                }
                
                
                
                
                int i=1;
                DefaultTableModel model=(DefaultTableModel) tableLoc.getModel();
                rs=st.executeQuery("select * from SwPkg");
                
               
//                while(rs.next()){
//                    if(rs.getString("swID").equals(txtID.getText())){
//                        
//                        while(rs1.next()){
//                            if(rs1.getString("eqID").equalsIgnoreCase(rs.getString("loc"))||rs1.getString("eqName").equalsIgnoreCase(rs.getString("loc")))
//                            model.addRow(new Object[]{i++,rs1.getString("eqID"),rs1.getString("eqName")});
////                        SN=rs.getInt("SN");
//                        }
//                        
//                    }
//                }
                while(rs.next()){
                    System.out.println(rs.getString("loc")+" "+rs.getString("swID")+" "+txtID.getText());
                    if(rs.getString("swID").equalsIgnoreCase(txtID.getText())){
                        Statement st1=con.createStatement();
                        ResultSet rs1=st1.executeQuery("select * from equipment");
                        while(rs1.next())
                        {
                            System.out.println(rs1.getString("eqID")+" "+rs.getString("loc"));
                            if(rs1.getString("eqID").equalsIgnoreCase(rs.getString("loc"))||rs1.getString("eqName")
                                    .equalsIgnoreCase(rs.getString("loc"))){
                                model.addRow(new Object[]{i++,rs1.getString("eqID"),rs1.getString("eqName")});
                                SN=rs.getInt("SN");
                            } 
                         }
                    }
                }
        }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtUpd = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtSize = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtRev = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableLoc = new javax.swing.JTable();
        labName = new javax.swing.JLabel();
        txtEqName = new javax.swing.JTextField();
        btnAdDev = new javax.swing.JButton();
        btnUpDev = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnUpd = new javax.swing.JButton();
        btnFinish = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Impact", 0, 48)); // NOI18N
        jLabel1.setText("SOFTWARE PACKAGE DETAILS");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Software ID:");

        txtID.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        txtID.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("Software Name:");

        txtName.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        txtName.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setText("Date of Updation:");

        txtUpd.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        txtUpd.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtUpd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUpdActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setText("Size (in Bytes):");

        txtSize.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        txtSize.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setText("Revision No:");

        txtRev.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        txtRev.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel7.setText("Location in devices:");

        tableLoc.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        tableLoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SN", "ID", "Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableLoc.setRowHeight(30);
        tableLoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableLocMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tableLocMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(tableLoc);

        labName.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        labName.setText("Location Name");

        txtEqName.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        txtEqName.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtEqName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEqNameActionPerformed(evt);
            }
        });

        btnAdDev.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnAdDev.setText("ADD device");
        btnAdDev.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnAdDev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdDevActionPerformed(evt);
            }
        });

        btnUpDev.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnUpDev.setText("UPDATE device");
        btnUpDev.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnUpDev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpDevActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(255, 102, 102));
        btnBack.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        btnBack.setText("BACK");
        btnBack.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 2, true));
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBackMouseExited(evt);
            }
        });
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnUpd.setBackground(new java.awt.Color(253, 202, 150));
        btnUpd.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        btnUpd.setText("UPDATE");
        btnUpd.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 51), 2, true));
        btnUpd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUpdMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUpdMouseExited(evt);
            }
        });
        btnUpd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdActionPerformed(evt);
            }
        });

        btnFinish.setBackground(new java.awt.Color(153, 255, 153));
        btnFinish.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        btnFinish.setText("FINISH");
        btnFinish.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 153, 0), 2, true));
        btnFinish.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFinishMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnFinishMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnFinishMouseExited(evt);
            }
        });
        btnFinish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinishActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(696, 696, 696)
                .addComponent(jLabel1))
            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1920, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(958, 958, 958)
                .addComponent(btnFinish, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUpd, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtUpd, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(30, 30, 30)
                                    .addComponent(jLabel5)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtSize, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(txtRev, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1600, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(labName)
                        .addGap(10, 10, 10)
                        .addComponent(txtEqName))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdDev, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpDev, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel1)
                .addGap(151, 151, 151)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtUpd, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtSize, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtRev, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labName)
                    .addComponent(txtEqName, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAdDev, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpDev, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnFinish, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                    .addComponent(btnUpd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void txtUpdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUpdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUpdActionPerformed

    private void txtEqNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEqNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEqNameActionPerformed

    private void btnAdDevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdDevActionPerformed
        String name=txtEqName.getText();
   
        
        if(name.equals("")||name.equals("")){
            JOptionPane.showMessageDialog(null,"Both fields are required!");
        }
        else{
            try{
                Connection con=ConnectionProvider.getCon();
                PreparedStatement ps=con.prepareStatement("insert into SwPkg(swID,name, size,dateOfUpdation,loc,revNo)values(?,?,?,?,?,?)");
                ps.setString(1,txtID.getText());
                ps.setString(2,txtName.getText());
                ps.setString(3,txtSize.getText());
                ps.setString(4,txtUpd.getText());
                ps.setString(5,name);
                ps.setString(6,txtRev.getText());
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null,"Device added successfully!");
               
                setVisible(false);
                new SearchSw(txtID.getText()).setVisible(true);
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
        }
    }//GEN-LAST:event_btnAdDevActionPerformed

    private void btnUpdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdActionPerformed
        JOptionPane.showMessageDialog(null,"All fields are editable now!");
        tableLoc.setEnabled(true);
         f=1;
            labName.setVisible(true);
            
            
            txtEqName.setVisible(true);
            
            btnAdDev.setVisible(true);
            btnAdDev.setEnabled(true);
            btnUpDev.setVisible(true);
            btnUpDev.setEnabled(false);
        
        txtName.setEditable(true);
        txtSize.setEditable(true);
        txtUpd.setEditable(true);
        txtRev.setEditable(true);
        btnUpd.setVisible(false);
        btnFinish.setVisible(true);
    }//GEN-LAST:event_btnUpdActionPerformed

    private void btnUpDevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpDevActionPerformed
        String name=txtEqName.getText();
       
        
        if(name.equals("")){
            JOptionPane.showMessageDialog(null,"Field is required!");
        }
        else{
            try{
                Connection con=ConnectionProvider.getCon();
                PreparedStatement ps=con.prepareStatement("update SwPkg set(loc=? where loc=?)");
                ps.setString(1,name);
                ps.setString(2,loc);
                
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null,"Device updated successfully!");
                setVisible(false);
                new SearchSw(txtID.getText()).setVisible(true);
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
        }
    }//GEN-LAST:event_btnUpDevActionPerformed

    private void tableLocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableLocMouseClicked
       if(f==0)
       {
           int index=tableLoc.getSelectedRow();
            TableModel model= tableLoc.getModel();
//        String sn=model.getValueAt(index,0).toString();
        
        
            String id=model.getValueAt(index, 1).toString();
//        String name=model.getValueAt(index, 2).toString();
       
            setVisible(false);
            new SearchRes(id).setVisible(true);
       }
       else{
           int index=tableLoc.getSelectedRow();
        TableModel model= tableLoc.getModel();
        String id=model.getValueAt(index,0).toString();
        
        SN=SN+Integer.parseInt(id)+1;
        String name=model.getValueAt(index, 2).toString();
        
        txtEqName.setText(name);
        
        
        btnAdDev.setEnabled(false);
        btnUpDev.setEnabled(true);
       }
    }//GEN-LAST:event_tableLocMouseClicked

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        setVisible(false);
        new SwPkg().setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnFinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinishActionPerformed
        String name=txtName.getText();
        String id=txtID.getText();
        String size=txtSize.getText();
        String dou=txtUpd.getText();
        String rev=txtRev.getText();
        if((name.equals("")||id.equals("")||size.equals("")||dou.equals("")||rev.equals(""))){
            JOptionPane.showMessageDialog(null,"All fields are required!!!");
        }
        else{
            try{
                Connection con=ConnectionProvider.getCon();
                PreparedStatement ps=con.prepareStatement("update SwPkg set name=?,size=?,dateOfUpdation=?,revNo=? where swID=?");
                ps.setString(1,name);
                ps.setString(2,size);
                ps.setString(3,dou);
                ps.setString(4,rev);
                ps.setString(5,id);
                
                ps.executeUpdate();
                
                JOptionPane.showMessageDialog(null,"Software updated successfully!");
                setVisible(false);
                new ManageUser().setVisible(true);
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
        }
        
        setVisible(false);
        new SwPkg().setVisible(true);
    }//GEN-LAST:event_btnFinishActionPerformed

    private void tableLocMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableLocMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tableLocMouseEntered

    private void btnBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseEntered
        btnBack.setBackground(new Color(255,51,51));
        btnBack.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnBackMouseEntered

    private void btnBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseExited
        btnBack.setBackground(new Color(255,102,102));
        btnBack.setForeground(Color.BLACK);
    }//GEN-LAST:event_btnBackMouseExited

    private void btnFinishMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFinishMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFinishMouseClicked

    private void btnFinishMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFinishMouseEntered
        btnFinish.setBackground(new Color(51,153,0));
        btnFinish.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnFinishMouseEntered

    private void btnFinishMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFinishMouseExited
        btnFinish.setBackground(new Color(153,255,153));
        btnFinish.setForeground(Color.BLACK);
    }//GEN-LAST:event_btnFinishMouseExited

    private void btnUpdMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdMouseEntered
        btnUpd.setBackground(new Color(255,153,51));
        btnUpd.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnUpdMouseEntered

    private void btnUpdMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdMouseExited
        btnUpd.setBackground(new Color(253,202,150));
        btnUpd.setForeground(Color.BLACK);
    }//GEN-LAST:event_btnUpdMouseExited

    private void btnUpdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchSw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchSw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchSw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchSw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchSw().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdDev;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnFinish;
    private javax.swing.JButton btnUpDev;
    private javax.swing.JButton btnUpd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labName;
    private javax.swing.JTable tableLoc;
    private javax.swing.JTextField txtEqName;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtRev;
    private javax.swing.JTextField txtSize;
    private javax.swing.JTextField txtUpd;
    // End of variables declaration//GEN-END:variables
}
